spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sample1?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: UNTiBN9fu67mbwm_g_OD
    secret: 5xhMMhLCzd